In [1]:
import numpy as np
import os

In [2]:
dir = "DATA"

In [3]:
train_file = np.load(os.path.join(dir, "train.npz"))
train_data = train_file["data"]
print("train_data's shape", train_data.shape)

train_data's shape (10000, 50, 110, 6)


In [4]:
test_file = np.load(os.path.join(dir, "test_input.npz"))
test_data = test_file["data"]
print("test_data's shape", test_data.shape)

test_data's shape (2100, 50, 50, 6)


In [5]:
def viewPercentiles(data, percentile_interval=5):
    percentiles = np.arange(percentile_interval, 100, percentile_interval) # [5, 10, 15, ..., 95]
    p_values = np.percentile(data, percentiles)

    for p, value in zip(percentiles, p_values):
        print(f"{p}th percentile: {value}")

In [11]:
# xvel = np.mean(np.abs(train_data[:100, 0, :, 2]), axis=(1))
pos_diff = np.max(train_data[:, 0, :, 0], axis=1) - np.min(train_data[:, 0, :, 0], axis=1)
np.argmin(pos_diff)
# viewPercentiles(pos_diff.flatten(), 5)

9717

In [14]:
train_data[:2, 0, :2, :]

array([[[ 3.38593222e+02, -6.72215748e+02, -5.32538052e+00,
          1.61518358e+00,  2.84662927e+00,  0.00000000e+00],
        [ 3.38061060e+02, -6.72053753e+02, -5.32538052e+00,
          1.61518358e+00,  2.84649174e+00,  0.00000000e+00]],

       [[ 3.14116107e+03,  1.71256435e+03,  2.59167472e+00,
         -2.80391940e+00, -8.28396968e-01,  0.00000000e+00],
        [ 3.14142933e+03,  1.71227455e+03,  2.59167472e+00,
         -2.80391940e+00, -8.28011459e-01,  0.00000000e+00]]])

In [ ]:
data = train_data[:, 0, :, 4]
maximum_heading = np.max(data, axis=1)
minimum_heading = np.min(data, axis=1)
np.argsort(maximum_heading - minimum_heading)[::-1]
# maximum_heading.shape
# indices = [i for i, row in enumerate(data) if len(np.unique(row)) > 2]
# print(f"Some example indices where ego heading changes = {indices[:5]}")

array([3930, 6148, 2651, ..., 7945, 5723, 4894], dtype=int64)

In [17]:
for scen in range(10000):
    data = train_data[scen, 0, :, 2]
    indices = np.where(data == 0)[0]
    if len(indices) > 4:
        print(f"Scen={scen}, Indices={indices}")

Scen=1582, Indices=[  0   1   2 108 109]
Scen=3131, Indices=[  0   1 107 108 109]
Scen=5503, Indices=[0 1 2 3 4]
Scen=5989, Indices=[0 1 2 3 4]
Scen=6345, Indices=[  0   1 107 108 109]
Scen=8861, Indices=[  0   1   2   3 109]
Scen=9945, Indices=[  0   1 107 108 109]


In [56]:
ind = 2
print((train_data[ind, 0, :, 1][1:] - train_data[ind, 0, :, 1][:-1])[:40])
print((train_data[ind, 0, :, 3])[:40])

[3.16280705e-07 3.33053208e-07 3.82535291e-07 4.76171351e-07
 5.73187549e-07 6.39473114e-07 6.80221660e-07 7.85523980e-07
 8.96166569e-07 9.75043520e-07 1.06776685e-06 1.12907577e-06
 1.20148252e-06 1.26250302e-06 1.27174360e-06 1.35660173e-06
 1.37029190e-06 1.31509000e-06 1.20369947e-06 1.04953500e-06
 1.00580041e-06 9.23340792e-07 8.70981694e-07 8.93809954e-07
 8.82192580e-07 8.97151210e-07 9.15406872e-07 8.92978846e-07
 8.59638931e-07 7.83473695e-07 7.66129574e-07 8.76345041e-07
 9.00789189e-07 8.72988949e-07 8.17236241e-07 8.14235705e-07
 8.03711373e-07 7.82065740e-07 8.59907004e-07 8.65342543e-07]
[ 2.24186465e-06  2.24186465e-06  4.35088168e-06  1.02730053e-05
  4.10563302e-06  5.94621952e-08  9.14712189e-06  1.22544145e-05
  8.53282586e-06  5.41767236e-07  4.95920915e-06  1.46510934e-05
  1.42181131e-05  1.05346550e-05  1.02821861e-05  1.47682653e-05
  2.04386185e-05  1.35895101e-05  1.08010801e-05  1.14394931e-05
  7.90762044e-06  1.03569812e-05  1.49579051e-05  9.76863021e-06

In [59]:
(train_data[9594, 0, 1:, 2:4] - train_data[9594, 0, :-1, 2:4])[:50]

array([[ 0.00000000e+00,  0.00000000e+00],
       [-1.21973430e+01,  4.65767850e+00],
       [-4.91829141e-01,  1.81901877e-01],
       [ 4.38963374e-01, -1.62053212e-01],
       [-7.55837224e-02,  3.26143485e-02],
       [ 5.59786154e-03, -2.08674120e-02],
       [-1.17787172e-01,  4.88222510e-02],
       [-5.80907188e-02,  5.50643602e-03],
       [-3.01655402e-04,  2.79556889e-05],
       [ 2.54220322e-02,  3.15036950e-03],
       [ 3.30230835e-01, -1.33378894e-01],
       [-5.17073188e-01,  1.83706552e-01],
       [ 1.78622357e-01, -6.61493308e-02],
       [-6.46723027e-02,  2.31965140e-02],
       [ 4.37551069e-02, -2.40351179e-02],
       [-7.32637764e-02,  1.28642006e-02],
       [-1.41695564e-02,  5.06193977e-03],
       [ 5.46331894e-02, -2.22947318e-02],
       [ 8.55684270e-02, -2.43153562e-02],
       [-2.42571220e-01,  8.76999923e-02],
       [ 9.63821417e-02, -2.97211895e-02],
       [ 1.17338644e-01, -4.46532815e-02],
       [-5.57410600e-02,  3.67097734e-02],
       [ 1.

In [31]:
# Correlation between velocity and change in position

for ind in range(len(train_data)):
    del_x = (train_data[ind, 0, :, 0][1:] - train_data[ind, 0, :, 0][:-1]).flatten()
    vel_x = train_data[ind, 0, :, 2][:-1].flatten()

    corr = np.corrcoef(del_x, vel_x)
    if corr[0, 1] < 0.2:
        print(f"Index={ind}, Correlation={corr}")

Index=54, Correlation=[[ 1.         -0.01073548]
 [-0.01073548  1.        ]]
Index=141, Correlation=[[1.         0.14094629]
 [0.14094629 1.        ]]
Index=159, Correlation=[[ 1.        -0.0286219]
 [-0.0286219  1.       ]]
Index=285, Correlation=[[ 1.         -0.04445506]
 [-0.04445506  1.        ]]
Index=294, Correlation=[[1.         0.19605481]
 [0.19605481 1.        ]]
Index=295, Correlation=[[1.        0.1920903]
 [0.1920903 1.       ]]
Index=311, Correlation=[[ 1.         -0.10903148]
 [-0.10903148  1.        ]]
Index=328, Correlation=[[ 1.         -0.05178082]
 [-0.05178082  1.        ]]
Index=354, Correlation=[[1.         0.18640364]
 [0.18640364 1.        ]]
Index=366, Correlation=[[1.         0.12940088]
 [0.12940088 1.        ]]
Index=368, Correlation=[[1.         0.10633012]
 [0.10633012 1.        ]]
Index=376, Correlation=[[ 1.         -0.08241162]
 [-0.08241162  1.        ]]
Index=447, Correlation=[[1.         0.03010936]
 [0.03010936 1.        ]]
Index=464, Correlation=

In [53]:
x = train_data[:, 0, :, 1]
del_x = (x[:, 1:] - x[:, :-1]).flatten()
vel_x = train_data[:, 0, :, 3][:, :-1].flatten()

factors = vel_x / del_x
# print(vel_x[:5])
# print(del_x[:5])
# print(x[:5])
print(f"{factors[:5]}")
print(f"Mean factor={np.mean(factors)}")

# Assuming 'arr' is your numpy array
percentiles = np.arange(5, 100, 5) # [5, 10, 15, ..., 95]
p_values = np.percentile(factors, percentiles)

for p, value in zip(percentiles, p_values):
    print(f"{p}th percentile: {value}")

[ 9.97062312  8.07515369 13.68923066 11.95694393 10.79741669]
Mean factor=7.242413555480695
5th percentile: -0.09776724033733139
10th percentile: 5.229258080251622
15th percentile: 8.399457028391861
20th percentile: 9.262530121661351
25th percentile: 9.56044977259487
30th percentile: 9.751141865063532
35th percentile: 9.857292375648331
40th percentile: 9.919854450472567
45th percentile: 9.961423926906312
50th percentile: 9.993859352500806
55th percentile: 10.025776600282185
60th percentile: 10.066765277767438
65th percentile: 10.130989353058904
70th percentile: 10.237570340087114
75th percentile: 10.429745506928004
80th percentile: 10.86519103303356
85th percentile: 11.89455713118868
90th percentile: 14.06515730895997
95th percentile: 19.792302873470884


In [41]:
train_data[:, 0, 50:, :2].shape

(10000, 60, 2)

In [9]:
ind = 1

for ind in range(100):
    print(f"Index={ind} max diff={np.max(data[ind]) - np.min(data[ind])}")


Index=0 max diff=0.009930460002847585
Index=1 max diff=0.007406358566250604
Index=2 max diff=0.05616076935668482
Index=3 max diff=0.006211947366350001
Index=4 max diff=0.004273306247238651
Index=5 max diff=0.03578788872566374
Index=6 max diff=0.05094238984491528
Index=7 max diff=1.585270226595424
Index=8 max diff=0.2348053485801993
Index=9 max diff=3.114786540792114e-05
Index=10 max diff=0.2582800419258689
Index=11 max diff=0.08331879253587571
Index=12 max diff=0.01669707183757918
Index=13 max diff=1.0035521953037314
Index=14 max diff=1.3641635699792505
Index=15 max diff=1.7067444820995092e-05
Index=16 max diff=4.898237206768519e-05
Index=17 max diff=0.011009351071068929
Index=18 max diff=1.9892533129173273e-05
Index=19 max diff=0.005989195409686329
Index=20 max diff=0.0005003987917642332
Index=21 max diff=0.01132336930958866
Index=22 max diff=0.0027137842835842085
Index=23 max diff=0.022303762470224253
Index=24 max diff=0.10106691082360797
Index=25 max diff=0.025428385871886006
Index=